source 'https://rubygems.org'
ruby "~> 2.2.0"
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-cross_origin', '~> 0.3.1'
gem 'capybara'
gem 'sinatra-contrib'
gem 'dalli'
gem 'activesupport'
gem 'rspec'
gem 'rack-test'
gem 'rerun'
gem 'chess', :github => "bcpearce/command-line-chess", :branch => 'serializing'
