source 'https://rubygems.org'
ruby "2.0.0"
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'dalli'
gem 'activesupport'
gem 'rspec'
gem 'rack-test'
gem 'chess', :github => "Hawkeye000/command-line-chess", :branch => 'master'
